// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceBusQueueClient.Models;

namespace ServiceBusQueueClient.Migrations
{
    [DbContext(typeof(DeviceContext))]
    [Migration("20190402214752_CreateDeviceMonitoringApiDB")]
    partial class CreateDeviceMonitoringApiDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiceBusQueueClient.Models.Device", b =>
                {
                    b.Property<string>("SerialNumber")
                        .ValueGeneratedOnAdd();

                    b.HasKey("SerialNumber");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ServiceBusQueueClient.Models.DeviceMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BatteryLevel");

                    b.Property<string>("SerialNumber");

                    b.Property<DateTime>("Timestamp");

                    b.Property<TimeSpan>("Uptime");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber");

                    b.ToTable("DeviceMessages");
                });

            modelBuilder.Entity("ServiceBusQueueClient.Models.DeviceMessage", b =>
                {
                    b.HasOne("ServiceBusQueueClient.Models.Device", "Device")
                        .WithMany("DeviceMessages")
                        .HasForeignKey("SerialNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
